# Matfis dengan Notebooks

Sumber: https://colab.research.google.com/github/drvinceknight/Python-Mathematics-Handbook/blob/master/02-Linear-algebra-with-Numpy.ipynb#scrollTo=5_aVvPK-J370

Kita dimungkinkan untuk mempelajari aljabar linier secara simbolik dengan library
[Sympy](http://www.sympy.org/en/index.html) tetapi untuk komputasi numerik library [Numpy](http://www.numpy.org/) adalah merupakan pilihan terbaik karena sudah terbukti menunjukkan performa yang baik.<br>
Berikut adalah deskripsi tentang Numpy:
> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]  useful linear algebra, Fourier transform, and random number capabilitie.

Di dalam bagian ini kita akan mempelajari bagaimana cara:
- memanipulasi matriks;
- memecahkan persamaan matriks;
- menghitung invers dan determinan matriks.

## Memanipulasi matriks

Dengan menggunakan Numpy kita bisa langsung membentuk sebuah matriks. Tinjau contoh berikut:  



$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix} 
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$

Pertama, kita perlu meng-import Numpy

In [1]:
import numpy as np


Sekarang kita dapat mendefinisikan A dan B:

In [3]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [4]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [5]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [6]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

Kita dapat mendapatkan berikut ini secara langsung:<br>
 

$ 5A, A^3, (A + B), (A - B),\text{dan} AB $  
 


In [7]:
5*A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [8]:
A**3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [9]:
A+B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [10]:
A-B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [11]:
A*B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

**Latihan**<br>

Hitung $A ^ 2 - 2 A + 3$ dengan <br>

$$ A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

## Memecahkan persamaan matriks <br>
Kita dapat menggunakan Numpy secara efisien untuk memecahkan sistem persamaan yang besar dengan bentuk:<br>
$$ Ax=b$$

Sebagai ilustrasi, mari selesaikan soal berikut:<br>
$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$



In [12]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Kita menggunakan perintah $ \text {linalg.solve}   $

In [13]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Kita dapat memverifikasi hasilnya dengan 

In [14]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])